# Generated by Django 5.1.1 on 2024-10-20 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="введите место выполнения привычки",
                        max_length=150,
                        null=True,
                        verbose_name="место выполнения привчки",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        help_text="введите время выполнения привычки",
                        null=True,
                        verbose_name="время выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Введите название привычки",
                        max_length=200,
                        verbose_name="привычка",
                    ),
                ),
                (
                    "is_enjoined",
                    models.BooleanField(
                        default=False,
                        help_text="укажите признак приятной привычки",
                        verbose_name="признак приятной привычки",
                    ),
                ),
                (
                    "periodic",
                    models.CharField(
                        blank=True,
                        help_text="введите периодичность выполнения привычки",
                        max_length=100,
                        null=True,
                        verbose_name="периодичность выполения привычки",
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        help_text="вознаграждение за выполнение привычки",
                        max_length=200,
                        null=True,
                        verbose_name="вознаграждение",
                    ),
                ),
                (
                    "time_action",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="введите длительность выполнения",
                        null=True,
                        verbose_name="длительность выполнения",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="укажите признак публичности привычки",
                        verbose_name="признак публичности привычки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habits",
                        verbose_name="связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Полезная привычка",
                "verbose_name_plural": "Полезные привычки",
            },
        ),
    ]
