# Generated by Django 5.1.1 on 2024-10-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="periodic",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="введите периодичность выполнения привычки в часах",
                null=True,
                verbose_name="периодичность выполения привычки",
            ),
        ),
    ]
